/**
 * Client Model
 * Schema definition and validation for clients table in Supabase
 * Handles transformation between database and application formats
 */

import Joi from 'joi';
import { isValidWhatsAppJID } from '../../shared/utils/phone-formatter.js';

/**
 * Joi schema for client validation
 * Based on Supabase clients table structure from CLAUDE.md
 */
export const clientSchema = Joi.object({
  // Primary Key (auto-generated by Supabase)
  id: Joi.number().integer().positive().optional(),

  // Timestamps (auto-managed by Supabase)
  created_at: Joi.date().iso().optional(),
  updated_at: Joi.date().iso().optional(),

  // ============================================
  // GoHighLevel Fields
  // ============================================

  // Location ID (unique identifier from GHL)
  location_id: Joi.string()
    .trim()
    .min(1)
    .max(255)
    .required()
    .description('GoHighLevel location ID (unique)'),

  // GHL OAuth tokens
  ghl_access_token: Joi.string()
    .trim()
    .min(1)
    .max(1000)
    .optional()
    .allow(null)
    .description('GoHighLevel OAuth access token'),

  ghl_refresh_token: Joi.string()
    .trim()
    .min(1)
    .max(1000)
    .optional()
    .allow(null)
    .description('GoHighLevel OAuth refresh token'),

  ghl_token_expiry: Joi.date()
    .iso()
    .optional()
    .allow(null)
    .description('GoHighLevel token expiration timestamp'),

  // Conversation provider ID
  conversation_provider_id: Joi.string()
    .trim()
    .min(1)
    .max(255)
    .optional()
    .allow(null)
    .description('GHL conversation provider ID for WhatsApp'),

  // ============================================
  // Evolution API Fields (WhatsApp)
  // ============================================

  // Instance name
  instance_name: Joi.string()
    .trim()
    .min(1)
    .max(255)
    .required()
    .description('Evolution API instance name'),

  // Instance API key
  instance_apikey: Joi.string()
    .trim()
    .min(1)
    .max(500)
    .optional()
    .allow(null)
    .description('Evolution API instance API key'),

  // Instance sender (WhatsApp JID format)
  instance_sender: Joi.string()
    .trim()
    .min(1)
    .max(100)
    .custom((value, helpers) => {
      if (!isValidWhatsAppJID(value)) {
        return helpers.error('any.invalid', {
          message: `Invalid WhatsApp JID format: ${value}. Expected format: {digits}@s.whatsapp.net`,
        });
      }
      return value;
    })
    .optional()
    .allow(null)
    .description('WhatsApp sender JID (format: 34684735362@s.whatsapp.net)'),

  // ============================================
  // Optional Configuration
  // ============================================

  // Per-client OpenAI API key override
  openai_apikey: Joi.string()
    .trim()
    .min(1)
    .max(500)
    .pattern(/^sk-/)
    .optional()
    .allow(null)
    .description('OpenAI API key override (optional, starts with sk-)'),

  // Webhook secret for validation
  webhook_secret: Joi.string()
    .trim()
    .min(8)
    .max(255)
    .optional()
    .allow(null)
    .description('Webhook secret for validation (optional)'),

  // ============================================
  // Status & Metadata
  // ============================================

  // Active status
  is_active: Joi.boolean()
    .default(true)
    .optional()
    .description('Whether client is active'),

  // Additional metadata (JSON field)
  metadata: Joi.object()
    .optional()
    .allow(null)
    .description('Additional client metadata (JSON)'),
}).options({
  stripUnknown: true, // Remove unknown fields
  abortEarly: false, // Return all errors, not just first
});

/**
 * Validate client data against schema
 * @param {Object} data - Client data to validate
 * @param {Object} options - Joi validation options
 * @returns {Object} Validation result { error, value }
 */
export function validateClient(data, options = {}) {
  const validationOptions = {
    abortEarly: false,
    stripUnknown: true,
    ...options,
  };

  return clientSchema.validate(data, validationOptions);
}

/**
 * Schema for client creation (required fields only)
 */
export const clientCreateSchema = Joi.object({
  location_id: Joi.string().trim().min(1).max(255).required(),
  instance_name: Joi.string().trim().min(1).max(255).required(),
  ghl_access_token: Joi.string().trim().min(1).max(1000).optional().allow(null),
  ghl_refresh_token: Joi.string().trim().min(1).max(1000).optional().allow(null),
  ghl_token_expiry: Joi.date().iso().optional().allow(null),
  conversation_provider_id: Joi.string().trim().min(1).max(255).optional().allow(null),
  instance_apikey: Joi.string().trim().min(1).max(500).optional().allow(null),
  instance_sender: Joi.string()
    .trim()
    .custom((value, helpers) => {
      if (value && !isValidWhatsAppJID(value)) {
        return helpers.error('any.invalid');
      }
      return value;
    })
    .optional()
    .allow(null),
  openai_apikey: Joi.string().trim().pattern(/^sk-/).optional().allow(null),
  webhook_secret: Joi.string().trim().min(8).max(255).optional().allow(null),
  is_active: Joi.boolean().default(true).optional(),
  metadata: Joi.object().optional().allow(null),
}).options({ stripUnknown: true, abortEarly: false });

/**
 * Schema for client update (all fields optional except ID)
 */
export const clientUpdateSchema = Joi.object({
  id: Joi.number().integer().positive().required(),
  location_id: Joi.string().trim().min(1).max(255).optional(),
  instance_name: Joi.string().trim().min(1).max(255).optional(),
  ghl_access_token: Joi.string().trim().min(1).max(1000).optional().allow(null),
  ghl_refresh_token: Joi.string().trim().min(1).max(1000).optional().allow(null),
  ghl_token_expiry: Joi.date().iso().optional().allow(null),
  conversation_provider_id: Joi.string().trim().min(1).max(255).optional().allow(null),
  instance_apikey: Joi.string().trim().min(1).max(500).optional().allow(null),
  instance_sender: Joi.string()
    .trim()
    .custom((value, helpers) => {
      if (value && !isValidWhatsAppJID(value)) {
        return helpers.error('any.invalid');
      }
      return value;
    })
    .optional()
    .allow(null),
  openai_apikey: Joi.string().trim().pattern(/^sk-/).optional().allow(null),
  webhook_secret: Joi.string().trim().min(8).max(255).optional().allow(null),
  is_active: Joi.boolean().optional(),
  metadata: Joi.object().optional().allow(null),
})
  .min(2) // At least ID + one field to update
  .options({ stripUnknown: true, abortEarly: false });

// ============================================
// Transformers: Database ↔ Application
// ============================================

/**
 * Transform database row to application format
 * Converts snake_case to camelCase and handles data types
 *
 * @param {Object} dbRow - Database row from Supabase
 * @returns {Object} Client in application format
 *
 * @example
 * const dbRow = { location_id: 'loc-123', instance_name: 'my-instance' };
 * const appClient = dbToApp(dbRow);
 * // { locationId: 'loc-123', instanceName: 'my-instance' }
 */
export function dbToApp(dbRow) {
  if (!dbRow) return null;

  return {
    id: dbRow.id,
    createdAt: dbRow.created_at,
    updatedAt: dbRow.updated_at,

    // GHL fields
    locationId: dbRow.location_id,
    ghlAccessToken: dbRow.ghl_access_token,
    ghlRefreshToken: dbRow.ghl_refresh_token,
    ghlTokenExpiry: dbRow.ghl_token_expiry,
    conversationProviderId: dbRow.conversation_provider_id,

    // Evolution fields
    instanceName: dbRow.instance_name,
    instanceApikey: dbRow.instance_apikey,
    instanceSender: dbRow.instance_sender,

    // Optional fields
    openaiApikey: dbRow.openai_apikey,
    webhookSecret: dbRow.webhook_secret,

    // Status & metadata
    isActive: dbRow.is_active ?? true,
    metadata: dbRow.metadata,
  };
}

/**
 * Transform application format to database format
 * Converts camelCase to snake_case and prepares for DB insert/update
 *
 * @param {Object} appData - Client data in application format
 * @returns {Object} Client in database format
 *
 * @example
 * const appData = { locationId: 'loc-123', instanceName: 'my-instance' };
 * const dbData = appToDb(appData);
 * // { location_id: 'loc-123', instance_name: 'my-instance' }
 */
export function appToDb(appData) {
  if (!appData) return null;

  const dbData = {};

  // Only include defined fields (skip undefined, but allow null)
  if (appData.id !== undefined) dbData.id = appData.id;

  // GHL fields
  if (appData.locationId !== undefined) dbData.location_id = appData.locationId;
  if (appData.ghlAccessToken !== undefined) dbData.ghl_access_token = appData.ghlAccessToken;
  if (appData.ghlRefreshToken !== undefined) dbData.ghl_refresh_token = appData.ghlRefreshToken;
  if (appData.ghlTokenExpiry !== undefined) dbData.ghl_token_expiry = appData.ghlTokenExpiry;
  if (appData.conversationProviderId !== undefined)
    dbData.conversation_provider_id = appData.conversationProviderId;

  // Evolution fields
  if (appData.instanceName !== undefined) dbData.instance_name = appData.instanceName;
  if (appData.instanceApikey !== undefined) dbData.instance_apikey = appData.instanceApikey;
  if (appData.instanceSender !== undefined) dbData.instance_sender = appData.instanceSender;

  // Optional fields
  if (appData.openaiApikey !== undefined) dbData.openai_apikey = appData.openaiApikey;
  if (appData.webhookSecret !== undefined) dbData.webhook_secret = appData.webhookSecret;

  // Status & metadata
  if (appData.isActive !== undefined) dbData.is_active = appData.isActive;
  if (appData.metadata !== undefined) dbData.metadata = appData.metadata;

  return dbData;
}

/**
 * Transform array of database rows to application format
 * @param {Array} dbRows - Array of database rows
 * @returns {Array} Array of clients in application format
 */
export function dbToAppArray(dbRows) {
  if (!Array.isArray(dbRows)) return [];
  return dbRows.map(dbToApp).filter(Boolean);
}

/**
 * Sanitize client data for logging (remove sensitive fields)
 * @param {Object} client - Client data
 * @returns {Object} Sanitized client data
 */
export function sanitizeForLogging(client) {
  if (!client) return null;

  const { ghlAccessToken, ghlRefreshToken, instanceApikey, openaiApikey, webhookSecret, ...safe } =
    client;

  return {
    ...safe,
    ghlAccessToken: ghlAccessToken ? '[REDACTED]' : null,
    ghlRefreshToken: ghlRefreshToken ? '[REDACTED]' : null,
    instanceApikey: instanceApikey ? '[REDACTED]' : null,
    openaiApikey: openaiApikey ? '[REDACTED]' : null,
    webhookSecret: webhookSecret ? '[REDACTED]' : null,
  };
}

/**
 * Check if GHL tokens are expired
 * @param {Object} client - Client data
 * @returns {boolean} True if tokens are expired or missing
 */
export function isTokenExpired(client) {
  if (!client || !client.ghlTokenExpiry) return true;

  const expiry = new Date(client.ghlTokenExpiry);
  const now = new Date();

  return expiry <= now;
}

/**
 * Get time until token expiry in seconds
 * @param {Object} client - Client data
 * @returns {number|null} Seconds until expiry, or null if no expiry
 */
export function getTokenExpirySeconds(client) {
  if (!client || !client.ghlTokenExpiry) return null;

  const expiry = new Date(client.ghlTokenExpiry);
  const now = new Date();
  const diffMs = expiry - now;

  return Math.floor(diffMs / 1000);
}

// Default export
export default {
  clientSchema,
  clientCreateSchema,
  clientUpdateSchema,
  validateClient,
  dbToApp,
  appToDb,
  dbToAppArray,
  sanitizeForLogging,
  isTokenExpired,
  getTokenExpirySeconds,
};
